### PR TITLE
Prettify commit diff output by `delta` (optional)

### PR DESCRIPTION
**Pull request by EdmondFrank**
Prettify commit diff show by [delta](https://github.com/dandavison/delta)

image

### CODE REVIEW

**Comment by manateelazycat** [comment]
Thanks for patch, I will review this patch after I finish EAF Git client, should some months later.

Thanks again.

**Comment by manateelazycat** [comment]
这个补丁必须依赖 dash 吗？

**Comment by manateelazycat** [comment]
@EdmondFrank 大佬方便把 delta 的依赖加到 eaf-git dependencies.json 里面吗？ 
delta这个工具的颜色分析确实好看。

**Comment by EdmondFrank** [comment]
> 这个补丁必须依赖 dash 吗？

不一定，我改改

**Comment by EdmondFrank** [comment]
@manateelazycat 移除了dash的依赖，然后加上了dependencies, 不过这个delta 还不支持Ubuntu/Debian 通过apt直接安装，可能这个平台的用户还得手动安装

**Pull request merged**
